kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
  name: test-ng
  namespace: cbc-pipelines-tests
  labels:
    app: test-ng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-ng
      version: '1'
  template:
    metadata:
      labels:
        app: test-ng
        version: '1'
      annotations:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
        - resources:
          name: test-ng
          env:
            - name: TEST
              value: test
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          image: 'image-registry.openshift-image-registry.svc:5000/cbc-pipelines-tests/test-ng@sha256:8dc49afce648f14b3a48d3b96fbe30d704f445564b84b708396c84ab0ebfb4e4'
